version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.12
    volumes:
      - ..:/workspace
    command: sleep infinity
    networks:
      - dev-network
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0-debian
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: py-url-shortener
      MYSQL_USER: py-url-shortener
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dev-network
    command: --default-authentication-plugin=mysql_native_password






volumes:

  mysql-data:




networks:
  dev-network:
    driver: bridge